# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-04 19:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='project',
        ),
        migrations.AddField(
            model_name='expense',
            name='budget',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='budget.Budget'),
            preserve_default=False,
        ),
    ]
